# Generated by Django 4.0.1 on 2023-01-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('prod_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=50)),
                ('prod_lgu', models.CharField(max_length=50)),
                ('prod_buyer', models.CharField(max_length=50)),
                ('prod_cost', models.IntegerField(max_length=50)),
                ('prod_price', models.IntegerField(max_length=50)),
                ('prod_sale', models.IntegerField(max_length=50)),
                ('prod_outline', models.CharField(max_length=50)),
                ('prod_img', models.CharField(max_length=50)),
                ('prod_totalstock', models.IntegerField(max_length=50)),
                ('prod_properstock', models.IntegerField(max_length=50)),
            ],
            options={
                'db_table': 'prod',
                'managed': False,
            },
        ),
    ]
