# Generated by Django 4.0.1 on 2023-01-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysqlapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mem_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('mem_pass', models.CharField(max_length=15)),
                ('mem_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
    ]
